### ISSUE TITLE
added translation button on site for Spanish, English, and French languages

### ISSUE THREAD

**Issue by lertsoft** [MKorostoff/1-pixel-wealth#82] opened 2022-07-02 13:55 UTC
https://wealth.ronnycoste.com ---> this link is quicker

https://ipfs.io/ipfs/QmTzGYKDutfeB7i5ZrvEsAE3141Z1hyB53o1F1TeQArJjd/ ---> This link would make live forever on the internet but it is really slow

Made as many files to be accessed locally to preserve them the ones that are still available.

**Comment by MKorostoff** [comment] 2022-08-02 15:16
@lertsoft nice project, but would you mind clarifying on that page that your project was adapted from mine? I don't mind people making translations and adaptations, but yours is the first version I've seen to simply re-host my exact words and credit someone else.

**Comment by MKorostoff** [comment] 2022-08-09 16:59
also, closed as duplicate of #8

**Closed by MKorostoff** 2022-08-09 16:59 UTC

**Comment by lertsoft** [comment] 2022-08-12 14:37
Fixed the footer. Let me know if there is any other bugs or details that i can fix.
Besides missing links... for those i need to find the replacement data.

**Comment by MKorostoff** [comment] 2022-08-12 15:09
thanks @lertsoft
