### ISSUE TITLE
Needs message to avoid misunderstandings

### ISSUE THREAD

**Issue by pablohirafuji** [MKorostoff/1-pixel-wealth#32] opened 2020-05-12 09:53 UTC
It's missing the message that Jeff Bezos improves everyone's life. That he is rich in the same proportion that he generates value to others.

The way you put it, it appears to be a bad thing that we have someone as rich as Jeff Bezos. It ignores the fact that, in a voluntary transaction, both sides ends with more value than started. This is how wealth is created. It's not a fixed amount.

It's missing the message that Bezos created this amount of value to society.

**Comment by MKorostoff** [comment] 2020-05-12 15:14
That's not a bug, it's a feature. Closing, works as designed.

**Closed by MKorostoff** 2020-05-12 15:14 UTC
